FROM aursu/rpmbuild:7-build

USER root
RUN yum -y install \
        cyrus-sasl-devel \
        libevent-devel \
        memcached \
        python-sphinx \
        systemtap-sdt-devel \
    && yum clean all && rm -rf /var/cache/yum
