version: "3"
services:
  rocky8build:
    volumes:
      - rpm8rocky:/root/rpmbuild/RPMS
    build:
      context: .
      args:
        os: $RL8
        image: build-root
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

volumes:
  rpm8rocky:
    name: rpm8rocky
