name: RPM build
on: [push]
env:
  ARTIFACTORY_URL: https://rpmb.jfrog.io
  BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
  BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  RL8: 8.7.20221112
  RL8TAG: 8.7.20221112
  OS9: stream9-20221206.0
  OS9TAG: stream9-20221206.0
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - build: rocky8build
            uploader: rocky8bintray
            repo_path: rocky/8
    env:
      BINTRAY_REPO: ${{ matrix.repo }}
      BUILD: ${{ matrix.build }}
      UPLOADER: ${{ matrix.uploader }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: docker-compose -f docker-compose.yml build --no-cache $BUILD
      - run: docker-compose -f docker-compose.yml up --exit-code-from $BUILD $BUILD
      - run: docker-compose -f rpmbuild/docker-compose.bintray.yml pull $UPLOADER
      - run: docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm -e BINTRAY_USER=$BINTRAY_USER -e BINTRAY_API_KEY=$BINTRAY_API_KEY -e BINTRAY_REPO=$BINTRAY_REPO -e ARTIFACTORY_URL=$ARTIFACTORY_URL $UPLOADER
